# Generated by Django 3.0.4 on 2020-04-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='station_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='train',
            name='train_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
